# Generated by Django 5.1.1 on 2024-10-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0004_cliente_libros_preferidos_alter_cliente_libros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='fecha_prestamo',
            field=models.DateTimeField(),
        ),
    ]
